// Generating each fork's patch files from the canonical copies (D2, model (d)).
//
// The forks keep self-contained, offline-buildable patch directories — no
// build-time network, no submodule, no bootstrapping circularity — and drift
// becomes a red build in THIS repo rather than an invisible difference between
// two repositories nobody diffs.
//
// Output must be byte-stable: same inputs produce identical bytes, every time.
// No timestamps, no workshop version, no blob hashes. A generator whose output
// churns cannot be used as a `--check` gate, because every run would be drift.

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { ROOT } from './paths.js';
import { renderBody } from './render.js';

export const MARKER_PREFIX = 'GENERATED from rn-media-engine patches/';

/** The banner every generated file opens with. */
export function generatedMarker(patchId) {
  return `${MARKER_PREFIX}${patchId} — edit THERE, sync here; local edits will be overwritten`;
}

/**
 * Resolve a fork's checkout: --<fork>-path, then $WORKSHOP_FORK_<FORK>, then
 * the manifest default (which assumes the forks sit beside this repo).
 */
export function forkPath(forkName, fork, flags = {}) {
  const fromFlag = flags[`${forkName}-path`];
  if (typeof fromFlag === 'string') return resolve(fromFlag);
  const fromEnv = process.env[`WORKSHOP_FORK_${forkName.toUpperCase()}`];
  if (fromEnv) return resolve(fromEnv);
  return resolve(ROOT, fork.defaultLocalPath);
}

/**
 * Pull the human prose out of a patch's docs.md.
 *
 * Two shapes exist. Patches migrated from a fork carry the original header
 * verbatim inside a ```text fence — that fence IS the fork's own prose, so it
 * round-trips exactly. Patches documented here first (the darwin-only ones,
 * which had no header at all in the fork) are plain markdown; those are emitted
 * as-is, which reads fine as text and is better than the nothing they have now.
 */
export function prosePartsFrom(docsFile) {
  const md = readFileSync(docsFile, 'utf8');
  const title = /^\*\*(.+?)\*\*\s*$/m.exec(md)?.[1]?.replace(/\s+/g, ' ') ?? '';
  const fence = /```text\n([\s\S]*?)\n```/.exec(md);
  if (fence) return { title, body: fence[1] };
  // Markdown-native docs: drop the H1 and the bold title line, keep the rest.
  const body = md
    .replace(/^#\s+.*\n/, '')
    .replace(/^\*\*.+?\*\*\s*\n/m, '')
    .trim();
  return { title, body };
}

/** The WORKSHOP block: what this patch is, and where to edit it. */
function workshopBlock(patch, forkName, fork) {
  const lines = [
    'WORKSHOP',
    `    Canonical source   rn-media-engine patches/${patch.id}/`,
    `    Kind               ${patch.kind === 'anchored' ? `anchored — ${patch.transforms.length} declared transforms, no line numbers` : 'unified diff'}`,
    `    Marker             ${patch.marker.split('\n')[0]}${patch.marker.includes('\n') ? ' …' : ''}`,
    `    Dependency         ${patch.deps.join(', ')}`,
    `    Platforms          ${patch.scope === 'shared' ? 'android + darwin (shared)' : `${patch.scope} only`}`,
    `    Variants           ${patch.variants.join(', ')}${patch.variants.length === 1 ? ` ONLY — gated to the ${patch.variants[0]} variant` : ''}`,
    `    Applied by         ${fork.appliedBy.byDep?.[patch.deps[0]] ?? fork.appliedBy.default}`,
  ];
  if (patch.asymmetry) {
    lines.push('', '    CROSS-PLATFORM ASYMMETRY');
    for (const l of wrapAt(patch.asymmetry, 68)) lines.push(`        ${l}`);
  }
  lines.push(
    '',
    '    Do not edit this file. Edit the canonical copy in rn-media-engine and',
    '    run `./workshop sync`; `./workshop sync --check` fails the build if this',
    '    file and the canonical copy have drifted.',
  );
  return lines.join('\n');
}

function wrapAt(text, width) {
  const out = [];
  let line = '';
  for (const w of String(text).split(/\s+/).filter(Boolean)) {
    if (line && line.length + 1 + w.length > width) {
      out.push(line);
      line = w;
    } else line = line ? `${line} ${w}` : w;
  }
  if (line) out.push(line);
  return out;
}

/**
 * The full generated file for one (patch, fork): header prose + WORKSHOP block
 * + diff body.
 * @returns {Promise<string>}
 */
export async function generateForkFile(patch, forkName, fork, ctx) {
  const { title, body: prose } = prosePartsFrom(patch.docsFile);
  const diff = await renderBody(patch, ctx);
  return [generatedMarker(patch.id), '', title, '', prose, '', workshopBlock(patch, forkName, fork), '', diff].join('\n');
}

/**
 * Split a fork file into (header, diff body). The body is everything from the
 * first `diff --git` or `--- ` line on — which is exactly what `git apply`
 * consumes, and the only part whose bytes are allowed to be load-bearing.
 */
export function splitForkFile(text) {
  const lines = text.split('\n');
  const i = lines.findIndex((l) => l.startsWith('diff --git ') || /^--- (a\/|\/dev\/null)/.test(l));
  if (i < 0) return { header: text, body: '' };
  return { header: lines.slice(0, i).join('\n'), body: lines.slice(i).join('\n') };
}

/** Which patches belong to a fork, in the order the fork's own map declares. */
export function patchesForFork(fork, patchesById) {
  return Object.entries(fork.files).map(([id, filename]) => {
    const patch = patchesById.get(id);
    if (!patch) throw new Error(`manifest/forks.json maps "${id}", which is not a patch`);
    if (patch.status !== 'active') throw new Error(`manifest/forks.json maps "${id}", which is ${patch.status}`);
    if (!patch.platforms.includes(fork.platform)) {
      throw new Error(`manifest/forks.json maps "${id}" into the ${fork.platform} fork, but the patch declares platforms ${patch.platforms.join(', ')}`);
    }
    return { patch, filename };
  });
}

/**
 * Every active patch that targets a platform but is NOT mapped into that fork.
 * A patch we apply somewhere but sync nowhere is exactly the hand-copying this
 * command exists to end, so it is an error rather than a shrug.
 */
export function unmappedForPlatform(fork, patches) {
  const mapped = new Set(Object.keys(fork.files));
  return patches.filter((p) => p.status === 'active' && p.platforms.includes(fork.platform) && !mapped.has(p.id)).map((p) => p.id);
}

export function readForkFile(root, fork, filename) {
  const p = join(root, fork.patchDir, filename);
  return existsSync(p) ? { path: p, text: readFileSync(p, 'utf8') } : { path: p, text: null };
}

export function writeForkFile(root, fork, filename, content) {
  writeFileSync(join(root, fork.patchDir, filename), content);
}
